name: Destroy Terraform Infrastructure

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip Lambda code
      run: |
        cd src
        zip ../src.zip index.js  # Ensure this matches the location of your Lambda code
        cd ..

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan (Destroy)
      run: terraform plan -destroy -out=tfplan

    - name: Terraform Apply (Destroy)
      run: terraform apply -auto-approve tfplan
